const MIN_STEP_TWO_PERCENT = 60;
const MIN_STEP_THREE_PERCENT = 20;
const MIN_SIMILARITY_PERCENT = 60;

module.exports = {
  MIN_STEP_TWO_PERCENT,
  MIN_STEP_THREE_PERCENT,
  MIN_SIMILARITY_PERCENT
};
